services:
  web:
    build: .
    command: uv run python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/app
      - venv:/app/.venv
    ports:
      - "8000:8000"
    env_file:
      - src/.env
    working_dir: /app/app

volumes:
  venv:
